### PR TITLE
fix: fix installation description in README

### PR DESCRIPTION
**Pull request by amarlankri**

### CODE REVIEW

**Review by na-ji — APPROVED** [review]

**Review by na-ji — CHANGES_REQUESTED** [review]
You commit message should be `doc` type

**Comment by amarlankri** [comment]
> You commit message should be `doc` type

Does `doc` trigger new version with `semantic-release`?

**Comment by na-ji** [comment]
> > You commit message should be `doc` type
> 
> Does `doc` trigger new version with `semantic-release`?

No but we don't want a new version, no?

**Comment by amarlankri** [comment]
> No but we don't want a new version, no?

Actually, I don't know how [npm Readme](https://www.npmjs.com/package/@algoan/eslint-config-react) is built. Is it built from the `README.md` published on npm or the one on GitHub?

If it is based on published `README.md`, I think we should publish a new version of the package since npm's Readme is misleading.

**Comment by na-ji** [comment]
> > No but we don't want a new version, no?
> 
> Actually, I don't know how [npm Readme](https://www.npmjs.com/package/@algoan/eslint-config-react) is built. Is it built from the `README.md` published on npm or the one on GitHub?
> 
> If it is based on published `README.md`, I think we should publish a new version of the package since npm's Readme is misleading.

You're right

**Review by na-ji — APPROVED** [review]

**Pull request merged**
