### PR TITLE
enforce naming conventions for everything

### PR DESCRIPTION
**Pull request by na-ji**
Hello,

In this pull request, I added rules to enforce naming convention. Those rules are not perfect, since they can't distinguish some types. Like for instance variable can be camelCase and PascalCase because we can't distinguish components from normal variable. It's possible to distinguish between the two by enabling type information, but that would slow down eslint by a lot.

If you want more information, see this reference: 

https://github.com/typescript-eslint/typescript-eslint/blob/master/packages/eslint-plugin/docs/rules/naming-convention.md

Result on demo-webapp:
```
./src/pages/_app.tsx
12:38  Error: Parameter name `Component` must match one of the following formats: camelCase  @typescript-eslint/naming-convention

./src/pages/_document.tsx
12:24  Error: Parameter name `App` must match one of the following formats: camelCase  @typescript-eslint/naming-convention
20:13  Warning: Do not include stylesheets manually. See: https://nextjs.org/docs/messages/no-css-tags.  @next/next/no-css-tags
```

Result on dashboard-webapp:
```

/Users/naji/www/aden-report-webapp/src/calculators/synthesis-calculator.ts
  207:5  error  Parameter name `TransactionCategory` must match one of the following formats: camelCase  @typescript-eslint/naming-convention
  256:5  error  Parameter name `TransactionCategory` must match one of the following formats: camelCase  @typescript-eslint/naming-convention

/Users/naji/www/aden-report-webapp/src/model/auth.ts
  16:3  error  Type Property name `preferred_username` must match one of the following formats: camelCase  @typescript-eslint/naming-convention
  17:3  error  Type Property name `given_name` must match one of the following formats: camelCase          @typescript-eslint/naming-convention
  18:3  error  Type Property name `family_name` must match one of the following formats: camelCase         @typescript-eslint/naming-convention
  21:3  error  Type Property name `resource_access` must match one of the following formats: camelCase     @typescript-eslint/naming-convention
  25:3  error  Type Property name `access_token` must match one of the following formats: camelCase        @typescript-eslint/naming-convention
  26:3  error  Type Property name `expires_in` must match one of the following formats: camelCase          @typescript-eslint/naming-convention
  27:3  error  Type Property name `refresh_expires_in` must match one of the following formats: camelCase  @typescript-eslint/naming-convention
  28:3  error  Type Property name `refresh_token` must match one of the following formats: camelCase       @typescript-eslint/naming-convention
  29:3  error  Type Property name `token_type` must match one of the following formats: camelCase          @typescript-eslint/naming-convention
  30:3  error  Type Property name `session_state` must match one of the following formats: camelCase       @typescript-eslint/naming-convention

/Users/naji/www/aden-report-webapp/src/modules/application/reducer.ts
  14:3  error  Type Property name `per_page` must match one of the following formats: camelCase  @typescript-eslint/naming-convention

/Users/naji/www/aden-report-webapp/src/pages/_app.tsx
  27:5  error  Type Property name `Cypress` must match one of the following formats: camelCase  @typescript-eslint/naming-convention

/Users/naji/www/aden-report-webapp/src/pages/_document.tsx
  13:24  error  Parameter name `App` must match one of the following formats: camelCase  @typescript-eslint/naming-convention

/Users/naji/www/aden-report-webapp/src/shared-components/atomic-components/button.tsx
  45:14  warning  Do not use <img>. Use Image from 'next/image' instead. See https://nextjs.org/docs/messages/no-img-element  @next/next/no-img-element

/Users/naji/www/aden-report-webapp/src/shared-components/icons/history-arrow-icon.tsx
  3:11  error  Interface name `historyArrowIconProps` must match one of the following formats: PascalCase  @typescript-eslint/naming-convention

/Users/naji/www/aden-report-webapp/src/shared-components/icons/language-flag.tsx
  16:10  warning  Do not use <img>. Use Image from 'next/image' instead. See https://nextjs.org/docs/messages/no-img-element  @next/next/no-img-element

/Users/naji/www/aden-report-webapp/src/store/reducers/auth/auth-selectors.ts
  36:10  error  Variable name `_rest` must match one of the following formats: camelCase, PascalCase, UPPER_CASE  @typescript-eslint/naming-convention

/Users/naji/www/aden-report-webapp/src/store/reducers/auth/auth-thunks.ts
   53:7   error  Object Literal Property name `grant_type` must match one of the following formats: camelCase, PascalCase          @typescript-eslint/naming-convention
   54:7   error  Object Literal Property name `client_id` must match one of the following formats: camelCase, PascalCase           @typescript-eslint/naming-convention
   59:7   error  Object Literal Property name `grant_type` must match one of the following formats: camelCase, PascalCase          @typescript-eslint/naming-convention
   60:7   error  Object Literal Property name `client_id` must match one of the following formats: camelCase, PascalCase           @typescript-eslint/naming-convention
   70:7   error  Object Literal Property name `refresh_token` must match one of the following formats: camelCase, PascalCase       @typescript-eslint/naming-convention
  143:64  error  Object Literal Property name `expires_in` must match one of the following formats: camelCase, PascalCase          @typescript-eslint/naming-convention
  143:79  error  Object Literal Property name `refresh_expires_in` must match one of the following formats: camelCase, PascalCase  @typescript-eslint/naming-convention

/Users/naji/www/aden-report-webapp/src/test-utils/mock-config.ts
  55:13  error  Object Literal Property name `CIVIL_PARTNERSHIP` must match one of the following formats: camelCase, PascalCase    @typescript-eslint/naming-convention
  70:13  error  Object Literal Property name `OWNER_WITH_MORTGAGE` must match one of the following formats: camelCase, PascalCase  @typescript-eslint/naming-convention
  71:13  error  Object Literal Property name `HOUSED_BY_EMPLOYER` must match one of the following formats: camelCase, PascalCase   @typescript-eslint/naming-convention
  72:13  error  Object Literal Property name `HOUSED_BY_FAMILY` must match one of the following formats: camelCase, PascalCase     @typescript-eslint/naming-convention
  73:13  error  Object Literal Property name `HOUSED_BY_FRIEND` must match one of the following formats: camelCase, PascalCase     @typescript-eslint/naming-convention

/Users/naji/www/aden-report-webapp/src/test-utils/server.ts
  24:42  error  Type Property name `access_token` must match one of the following formats: camelCase                        @typescript-eslint/naming-convention
  26:11  error  Object Literal Property name `access_token` must match one of the following formats: camelCase, PascalCase  @typescript-eslint/naming-convention

/Users/naji/www/aden-report-webapp/src/utils/use-recategorization-modal.tsx
  11:3  error  Type Property name `RecategorizationModal` must match one of the following formats: camelCase  @typescript-eslint/naming-convention

/Users/naji/www/aden-report-webapp/src/utils/use-transaction-modal.tsx
  12:3  error  Type Property name `TransactionModal` must match one of the following formats: camelCase  @typescript-eslint/naming-convention

/Users/naji/www/aden-report-webapp/src/utils/use-visible-element.ts
  3:11  error  Interface name `useVisibleElementParam` must match one of the following formats: PascalCase  @typescript-eslint/naming-convention

/Users/naji/www/aden-report-webapp/src/widgets/bank-statements/accounts-filter.tsx
  81:23  warning  Do not use <img>. Use Image from 'next/image' instead. See https://nextjs.org/docs/messages/no-img-element  @next/next/no-img-element

/Users/naji/www/aden-report-webapp/src/widgets/cofidis-debt-consolidation-synthesis/explicit-indicator-messages.ts
   5:3  error  Object Literal Property name `AVERAGE_MONEY` must match one of the following formats: camelCase, PascalCase   @typescript-eslint/naming-convention
  15:3  error  Object Literal Property name `CARD_TYPE` must match one of the following formats: camelCase, PascalCase       @typescript-eslint/naming-convention
  20:3  error  Object Literal Property name `NEGATIVE_VALUE` must match one of the following formats: camelCase, PascalCase  @typescript-eslint/naming-convention

✖ 40 problems (37 errors, 3 warnings)
```

Thanks.

### CODE REVIEW

**Comment by amarlankri** [comment]
When I see the log you added, I see several cases where the error are "normal". For instance in the demo:

```
./src/pages/_app.tsx
12:38  Error: Parameter name `Component` must match one of the following formats: camelCase  @typescript-eslint/naming-convention
```
and in the dashboard, all errors related to snake case used by OAuth variables.

So, the idea would be to disabled the rules locally?

**Comment by na-ji** [comment]
> When I see the log you added, I see several cases where the error are "normal". For instance in the demo:
> 
> ```
> ./src/pages/_app.tsx
> 12:38  Error: Parameter name `Component` must match one of the following formats: camelCase  @typescript-eslint/naming-convention
> ```
> 
> and in the dashboard, all errors related to snake case used by OAuth variables.
> 
> So, the idea would be to disabled the rules locally?

Yes exactly! In the case of next components, we can say that it is rare enough to receive a Component as a parameter, so we can disable it there. And in the case of snake_case property for objects coming from the backend, we can ignore them locally too since there are rare too. If you don't agree with me, we can loosen the rules, but I am afraid that it will used in other cases.

**Comment by amarlankri** [comment]
> > When I see the log you added, I see several cases where the error are "normal". For instance in the demo:
> > ```
> > ./src/pages/_app.tsx
> > 12:38  Error: Parameter name `Component` must match one of the following formats: camelCase  @typescript-eslint/naming-convention
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > and in the dashboard, all errors related to snake case used by OAuth variables.
> > So, the idea would be to disabled the rules locally?
> 
> Yes exactly! In the case of next components, we can say that it is rare enough to receive a Component as a parameter, so we can disable it there. And in the case of snake_case property for objects coming from the backend, we can ignore them locally too since there are rare too. If you don't agree with me, we can loosen the rules, but I am afraid that it will used in other cases.

I agree with you! It is better to enable this check and to handle the rare cases where they are not relevant manually 👍

**Review by amarlankri — APPROVED** [review]

**Review by mbeuil — APPROVED** [review]
That's a good idea. I'm team: better have lots of rules and disabling one, if needed, for a line

**Review by kajaksic — APPROVED** [review]

**Review by slatchma — APPROVED** [review]

**Review by KenzaYahia — APPROVED** [review]

**Review by charlies96 — APPROVED** [review]
👍

**Pull request merged**
